### ISSUE TITLE
Possibility to calibrate a pre-fitted estimator

### ISSUE THREAD

**Issue by tuvelofstrom** [ip200/venn-abers#1]
I really welcome this initiative!

I am considering using your implementation in a package but I need to be able to use it on already fitted estimators. I could not find any way of applying it to already fitted estimators, which is a must in my case. 

 The optimal would be if, at line 352 (VennAbersCV.fit), a check is made if the estimator is already fitted, assuming that the calibration data submitted for fitting has not been used for training. I would be happy to discuss my use case with you to find a good solution!

**Comment by tuvelofstrom** [comment]
An obvious alternative would be to add an additional parameter when initializing the VennAbersCalibrator, indicating whether the estimator is pre-fitted or not.

**Comment by tuvelofstrom** [comment]
As I commented in issue #2, I realized I do not need these changes, so I will close these issues. But I still think these improvements would be valuable, so consider re-opening the issues again.

**Comment by ip200** [comment]
Hi Tuwe, thank you once again for your suggestions. These have been incorporated now and are available here as well as on PyPi (soon on conda-forge too). Thanks, Ivan
