### ISSUE TITLE
Guarantees of Venn Abers?

### ISSUE THREAD

**Issue by karllandheer** [ip200/venn-abers#14]
Hello, I have been using your nice package. I used it to calibrate a large public dataset, and although the calibration has improved, it's far from perfect:

![image](https://github.com/ip200/venn-abers/assets/76697225/2da4c188-6c22-416b-9de4-554747652dc3)

![image](https://github.com/ip200/venn-abers/assets/76697225/bacc4ccb-abac-48a4-8b61-b2cb3f60469a)

I'm aware of some of the statistical guarantees of other conformal predictor methods, does this implementation of Venn Abers come with these guarantees? Or is my testing data perhaps from a different distribution from my calibration data (very possible).

**Comment by ip200** [comment]
Hi

Thank you for your message and my apologies for the delay in replying to
you. The Venn-Abers and their inductive counterpart do come with validity
guarantees (see e.g Proposition 1, Section 2 in
https://proceedings.neurips.cc/paper/2015/file/a9a1d5317a33ae8cef33961c34144f84-Paper.pdf)
, providing that the training, calibration and test data is all i.i.d. If
they are not, then unfortunately those guarantees do not hold.

One simple way to test this for your data would be to join and randomly
permute the whole dataset and then split it into train/calibration/test
splits manually, if this is possible? Under this scenario, IVAPs and most
CVAPs should achieve near ideal calibration.

Regards,

Ivan
