### ISSUE TITLE
Multiprobability outputs for CVAP

### ISSUE THREAD

**Issue by ehan03** [ip200/venn-abers#19]
Multiprobability outputs are only supported for the IVAP implementation as of writing. However, based on [this paper](https://proceedings.mlr.press/v60/manokhin17a/manokhin17a.pdf), it seems like the `n_splits` pairs of $(p_0, p_1)$ can be combined as
$$\left(1 - GM\left(1 - p_0 \right), GM\left(p_1 \right) \right) $$
to obtain an interval (see page 4 of the linked paper). Having multiprobability outputs for CVAP would be really nice

**Comment by ip200** [comment]
Hello thank you for your feedback and for the pull request. I will incorporate your suggestion and combine it with your git tidying change suggestions and will merge them all at once. Should be done in the next few days. Thank you, Ivan

**Comment by ip200** [comment]
Hi this has now been added, please see latest release 1.4.4

**Comment by ehan03** [comment]
Hey, thanks for the update! Will make sure to check it out, appreciate the work
